/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Reportes.ReporteActividad;
import Reportes.ReporteAdministrador;
import Reportes.ReporteCambios;
import Reportes.ReporteControl;
import Reportes.ReporteInteresados;
import Reportes.ReporteObjetivo;
import Reportes.ReportePersonal;
import Reportes.ReporteProblema;
import Reportes.ReporteRequisito;
import Reportes.ReporteReuniones;
import Reportes.ReporteRiesgo;
import Reportes.ReporteServlet;
import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class Impresion extends javax.swing.JFrame {
//enviar ruta para guardar el pdf
    public static String ruta;
 
    /**
     * Creates new form Impresion
     */
    public Impresion() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnproyecto = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf.png"))); // NOI18N

        btnproyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdfproyecto.png"))); // NOI18N
        btnproyecto.setText("PROYECTO");
        btnproyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproyectoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdfrequisito.png"))); // NOI18N
        jButton1.setText("REQUISITO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdfactividades.png"))); // NOI18N
        jButton7.setText("ACTIVIDADES");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdfcontrol.png"))); // NOI18N
        jButton9.setText("CONTROL");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdfproblema.png"))); // NOI18N
        jButton2.setText("PROBLEMA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdfobjetivo.png"))); // NOI18N
        jButton3.setText("OBJETIVO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdfreunion.png"))); // NOI18N
        jButton4.setText("REUNIONES");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdfcambios.png"))); // NOI18N
        jButton5.setText("CAMBIOS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdfinteresados.png"))); // NOI18N
        jButton6.setText("INTERESADOS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdfriesgo.png"))); // NOI18N
        jButton8.setText("RIESGO");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdfadmin.png"))); // NOI18N
        jButton10.setText("ADMINISTRADOR");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdfpersonal.png"))); // NOI18N
        jButton11.setText("PERSONAL");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton9))
                .addGap(196, 196, 196))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnproyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproyectoActionPerformed
        JFileChooser dig=new JFileChooser();
        int option =dig.showSaveDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            File f=dig.getSelectedFile();
            String   f1=f.toString();
            ruta=f1;
             ReporteServlet report=new ReporteServlet();
        report.impre();
         JOptionPane.showMessageDialog(null, "IMPRESION  REALIZADO");
        }else{
            JOptionPane.showMessageDialog(null, "IMPRESION NO REALIZADO");
        }

       

    }//GEN-LAST:event_btnproyectoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 JFileChooser dig=new JFileChooser();
        int option =dig.showSaveDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            File f=dig.getSelectedFile();
            String   f1=f.toString();
            ruta=f1;
             ReporteRequisito report=new ReporteRequisito();
        report.reporte();
         JOptionPane.showMessageDialog(null, "IMPRESION  REALIZADO");
        }else{
            JOptionPane.showMessageDialog(null, "IMPRESION NO REALIZADO");
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 JFileChooser dig=new JFileChooser();
        int option =dig.showSaveDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            File f=dig.getSelectedFile();
            String   f1=f.toString();
            ruta=f1;
             ReporteProblema report=new ReporteProblema();
        report.reporte();
         JOptionPane.showMessageDialog(null, "IMPRESION  REALIZADO");
        }else{
            JOptionPane.showMessageDialog(null, "IMPRESION NO REALIZADO");
        }    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 JFileChooser dig=new JFileChooser();
        int option =dig.showSaveDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            File f=dig.getSelectedFile();
            String   f1=f.toString();
            ruta=f1;
             ReporteObjetivo report=new ReporteObjetivo();
        report.reporte();
         JOptionPane.showMessageDialog(null, "IMPRESION  REALIZADO");
        }else{
            JOptionPane.showMessageDialog(null, "IMPRESION NO REALIZADO");
        }      }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
JFileChooser dig=new JFileChooser();
        int option =dig.showSaveDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            File f=dig.getSelectedFile();
            String   f1=f.toString();
            ruta=f1;
             ReporteReuniones report=new ReporteReuniones();
        report.reporte();
         JOptionPane.showMessageDialog(null, "IMPRESION  REALIZADO");
        }else{
            JOptionPane.showMessageDialog(null, "IMPRESION NO REALIZADO");
        }       }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
JFileChooser dig=new JFileChooser();
        int option =dig.showSaveDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            File f=dig.getSelectedFile();
            String   f1=f.toString();
            ruta=f1;
             ReporteCambios report=new ReporteCambios();
        report.reporte();
         JOptionPane.showMessageDialog(null, "IMPRESION  REALIZADO");
        }else{
            JOptionPane.showMessageDialog(null, "IMPRESION NO REALIZADO");
        }      }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
JFileChooser dig=new JFileChooser();
        int option =dig.showSaveDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            File f=dig.getSelectedFile();
            String   f1=f.toString();
            ruta=f1;
             ReporteInteresados report=new ReporteInteresados();
        report.reporte();
         JOptionPane.showMessageDialog(null, "IMPRESION  REALIZADO");
        }else{
            JOptionPane.showMessageDialog(null, "IMPRESION NO REALIZADO");
        }  
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
JFileChooser dig=new JFileChooser();
        int option =dig.showSaveDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            File f=dig.getSelectedFile();
            String   f1=f.toString();
            ruta=f1;
             ReporteRiesgo report=new ReporteRiesgo();
        report.reporte();
         JOptionPane.showMessageDialog(null, "IMPRESION  REALIZADO");
        }else{
            JOptionPane.showMessageDialog(null, "IMPRESION NO REALIZADO");
        }      }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
JFileChooser dig=new JFileChooser();
        int option =dig.showSaveDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            File f=dig.getSelectedFile();
            String   f1=f.toString();
            ruta=f1;
             ReporteAdministrador report=new ReporteAdministrador();
        report.reporte();
         JOptionPane.showMessageDialog(null, "IMPRESION  REALIZADO");
        }else{
            JOptionPane.showMessageDialog(null, "IMPRESION NO REALIZADO");
        }       }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
JFileChooser dig=new JFileChooser();
        int option =dig.showSaveDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            File f=dig.getSelectedFile();
            String   f1=f.toString();
            ruta=f1;
             ReportePersonal report=new ReportePersonal();
        report.reporte();
         JOptionPane.showMessageDialog(null, "IMPRESION  REALIZADO");
        }else{
            JOptionPane.showMessageDialog(null, "IMPRESION NO REALIZADO");
        }       }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
JFileChooser dig=new JFileChooser();
        int option =dig.showSaveDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            File f=dig.getSelectedFile();
            String   f1=f.toString();
            ruta=f1;
             ReporteControl report=new ReporteControl();
        report.reporte();
         JOptionPane.showMessageDialog(null, "IMPRESION  REALIZADO");
        }else{
            JOptionPane.showMessageDialog(null, "IMPRESION NO REALIZADO");
        } 
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
JFileChooser dig=new JFileChooser();
        int option =dig.showSaveDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            File f=dig.getSelectedFile();
            String   f1=f.toString();
            ruta=f1;
             ReporteActividad report=new ReporteActividad();
        report.reporte();
         JOptionPane.showMessageDialog(null, "IMPRESION  REALIZADO");
        }else{
            JOptionPane.showMessageDialog(null, "IMPRESION NO REALIZADO");
        }     }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Impresion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnproyecto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
